okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-2ak2vmso7stdhczm.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: http://localhost:8080/api